# Generated by Django 4.2.16 on 2024-09-20 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quesiton_text',
            new_name='question_text',
        ),
    ]
