# Generated by Django 4.2.16 on 2024-10-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_sent_date_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sent_date',
            field=models.DateTimeField(verbose_name='sent date'),
        ),
    ]
