# Generated by Django 4.2.16 on 2024-10-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_sent_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='sent_date',
            new_name='sent_date_utc',
        ),
    ]
