# Generated by Django 4.2.16 on 2024-09-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasHere', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WasHere',
            new_name='Marks',
        ),
    ]
