# Generated by Django 4.2.16 on 2024-09-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasHere', '0002_rename_washere_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
