# Generated by Django 4.2.16 on 2024-10-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasHere', '0003_alter_marks_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='font_weight',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='location_left',
            field=models.DecimalField(decimal_places=2, default=20.22, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='location_rotation',
            field=models.DecimalField(decimal_places=2, default=-1.55, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='location_top',
            field=models.DecimalField(decimal_places=2, default=99.11, max_digits=5),
            preserve_default=False,
        ),
    ]
