name: Test EC2 SSH Connection

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Connection to EC2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Connected successfully!"
            uname -a
            whoami
